development:
  adapter: redis
  url: redis://localhost:6379/1
  host: localhost

test:
  adapter: async

production:
  adapter: redis
  url: <% ENV['REDISTOGO_URL'] %>
  channel_prefix: gallery_production
