development:
  adapter: redis
  url: redis://localhost:6379/1
  host: localhost

test:
  adapter: redis

production:
  adapter: redis
  url: redis://redistogo:a887a28ada2c33265c353af9993c8bc0@soldierfish.redistogo.com:9892/
  channel_prefix: gallery_production
