# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 76482e644472e00a21f6824db867739fcc9f4f2f3f2937e54e17310d831ef39e43ec0b3a35f1e4dbe7779dab5b07af4f4ba72772882114af686f675006e79ba6
  recaptcha_site_key: 6LfHBT0UAAAAAHtidqKmAqf-Ym-FSN7t-oMT-ToQ
  recaptcha_secret_key: 6LfHBT0UAAAAAFt4VYvhfjBysmXA
  facebook_app_id: 1977405342541239
  facebook_secret: 5c3bcc5b67790b607bb95b98a61a4f79

test:
  secret_key_base: f2da24e6ecdd187910c3ab86de6ba838096597c4a7b6a52fd3b624c02b4cab9c412df7db43ef34dae830abecf0609faabbe883149fe7b87de75fb45d745ef91a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  recaptcha_site_key: 6LfHBT0UAAAAAHtidqKmAqf-Ym-FSN7t-oMT-ToQ
  recaptcha_secret_key: 6LfHBT0UAAAAAFt4VYvhfjBysmXA
  facebook_app_id: 1977405342541239
  facebook_secret: 5c3bcc5b67790b607bb95b98a61a4f79
