default: &default
  :verbose: true
  :concurrency: 5
  :queues:
    - [mailer, 5]
    - [mailers, 5]
    - [default, 5]
    - [notification, 5]
    - [chats, 5]

development:
  <<: *default

production:
  <<: *default
  :concurrency: 5
